[versions]
agp = "8.5.0"
kotlin = "1.9.23"
extlib = "1.4.1"
okhttp = "5.0.0-alpha.14"
kotlinxSerializationJson = "1.4.1"

[libraries]
gradle-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
tachiyomi-lib = { module = "com.github.tachiyomiorg:extensions-lib", version.ref = "extlib" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
